spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        enabled: false

feign:
  url:
    user: http://localhost:8002
    product: http://localhost:8001
    auth: http://localhost:9000