
server:
  port: 9000

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器连接端口
    # Redis 服务器连接密码（默认为空）
    password:
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
  security:
    jwt:
      signingKey: 3fdrew24wwerwr234234
      expire: 3600000

