

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
      routes:
      - id: service-hi
        uri: http://localhost:8002
        predicates:
          - Path=/api/user/**
        filters:
          - name: AuthCheckFilter

      - id: product
        uri: http://localhost:8001
        predicates:
          - Path=/api/product/**
        filters:
          - name: AuthCheckFilter

      
      - id: auth
        uri: http://localhost:9000
        predicates:
          - Path=/api/auth/**
      
      - id: eureka
        uri: http://localhost:8761/
        predicates:
          - Path=/eureka/**
        filters:
          - StripPrefix=1
          - name: AuthCheckFilter
