
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: service-hi
        uri: lb://user
        predicates:
          - Path=/api/user/**

      - id: product
        uri: lb://product
        predicates:
          - Path=/api/product/**
      
      - id: eureka
        uri: http://localhost:8761/
        predicates:
          - Path=/eureka/**
        filters:
          - StripPrefix=1

      - id: admin-server
        uri: lb://admin-server
        predicates:
          - Path=/admin/**
        # filters:
        #   - StripPrefix=1