
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
      routes:
      - id: service-hi
        uri: lb://USER
        predicates:
          - Path=/api/user/**

      - id: product
        uri: lb://PRODUCT
        predicates:
          - Path=/api/product/**
      
      - id: eureka
        uri: http://localhost:8761/
        predicates:
          - Path=/eureka/**
        filters:
          - StripPrefix=1

      - id: admin-server
        uri: lb://ADMIN-SERVER
        predicates:
          - Path=/admin/**
        # filters:
        #   - StripPrefix=1