

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
      routes:
      - id: service-hi
        uri: lb:USER
        predicates:
          - Path=/api/user/**
        filters:
          - name: AuthCheckFilter

      - id: product
        uri: lb:PRODUCT
        predicates:
          - Path=/api/product/**
        filters:
          - name: AuthCheckFilter

      
      - id: auth
        uri: lb://AUTH-SERVER
        predicates:
          - Path=/api/auth/**
      
      - id: eureka
        uri: http://localhost:8761/
        predicates:
          - Path=/eureka/**
        filters:
          - StripPrefix=1
          - name: AuthCheckFilter

      - id: admin-server
        uri: lb://ADMIN-SERVER
        predicates:
          - Path=/admin/**
        # filters:
        #   - StripPrefix=1