message: hello test message


spring:
  boot:
    admin:
      client:
        enabled: false
        url: http://localhost:8000
  zipkin:
    enabled: false

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

